travis:
  secure:
    BINSTAR_TOKEN: a9JyR8twxBRy61ambvEVI4z6jdP1yme8n0oIZ8lW4bwXb/y+fU0c6t9h+iEdj1CtwhjVnaEpBh17yxYFbaxZIo4vf3rUxGLSpaoQn3Imhlh/gO+ScOiwHe8zw+zTfonhCUC2My8ytucgrVVsCscE4aUCUWhBixkcXwrfWgYbASMcw/dsBdC5L5Y/pY6Z9KK/OLr4sB4/9m8RLatracSVcU7pB0Cqr0TGJxGifbzDThnDUJShqhjqMGdTkTc7FeSR5EUCSxpohCEgSfKQhBJuvwtoAJmZNMQKHaTkxRkBk+uFOaQB6GUfWfrS4rgwEkXnemvcj+x7SRd3U04OtbpB/piLZGKTlHew5GL6O70w3UG2Q3Q2scyVU4tjSZQ3xaLvrajBG8NNsxsDG7YsIqYbzklex+6UYex2+vZJn7Q9NljETJWfoEk3NRJshPYK/7X713m2jXtavMiSprR5mmb28vkuTGl3i0Jx9PMNi7G9NZDQO4RmSOhfz9rc0h2X8B9FgWR3f4Y4t3Q5FnUxuIhK99kk3Bz+5rCFt99rl6eO7X0/ExDrFb8AWOseCzCaJNz/u7ul/p1WkG+mt2XoWixNwYNjNP1NT2YooPjfCol31OITkDX6zTKwJHQEMCCpgji25GRxhzIUq4Lm5E8peraU9Xjk6GEIw3/tMBzdC+qN1Qc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
