travis:
  secure:
    BINSTAR_TOKEN: iNHCHoWKrznAwkl5vxv/Fl7n1BIXhv+7dt3Vy2vMDeb0/hOfUCegsL3sBRiRpVibBygdHnLpHkyv7dc7qdiyhQCShNDROPyE+IU/0HOdGwmfp1XpTzO6YdYG5AxuxkDvMUeAggt9gs/Zx8tjJ4Q0F/jjfiUDWlIIcTqXi8/V9Y6lPF+6pvhhoKKEE7gFYfG5m4O4abYOVaXLOzjGrtVUSsF2Zy3d+8Z3OmSQ4h9evc3wrRO0lEeJ5qALuT1JtzNOcZKaNsRz9sjksZyRgZNDBysw6p5yIa2Mc5KH9Bqxw0vcEfQu2Wy36xnU5bV/rcyPJuAvYza6QOSvIwq4uwH19nQFJSZQ8wRbTHSn8k7LNcPv7UMG03eA7b1C3c1uHw+/R1YivLo3WQkvLYE+j/Ifg9tMriUvUWqadzarBbBqPLTch+o+DGi1KZgMXoN5MReqdClSv4i1eXLvSMdg2hfCYjjDjS2dIsLMcAgWiSHGiXdm2oY9lPMq1kHo7iTRGEv4E8TXGsxZbFdIJUZkXZx8e1Q9JNZJfqO2iMtFMhRIo22hZ4TST1Xno1/tYSkwPgqhceJzTLun6BH740fnGVx0CV53cyQwzcwC7qUGeFvlUBpgb/0GbBM2cMtG7mWfQWpYb5WH9P+AGvDohozLHjfMXEysJOfpXKZzjw/RyVpi+v0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
